### ISSUE TITLE
Image split into over 100 tiles doesn't merge properly

### ISSUE THREAD

**Issue by rahidz** [ptrsuder/IEU.Core#13]
When I try to run IEU on an image and it generates more than 100 tiles, it splits the 100+th tiles into a separate folder, but doesn't properly merge them (I have to manually cut-and-paste the 2nd folder's contents into the 1st).

![bug1](https://user-images.githubusercontent.com/22056619/69005096-ee345d00-08ea-11ea-9408-573c29752b4d.jpg)

![bug2](https://user-images.githubusercontent.com/22056619/69005099-ef658a00-08ea-11ea-9f92-3d30f2097573.jpg)

**Comment by ptrsuder** [comment]
Show screens of main tab, settings. What version? Is rule system disabled?
