### ISSUE TITLE
Crash on Merging (Couldn't find last HR tile index for), no output given. 

### ISSUE THREAD

**Issue by NetyashaRoozi** [ptrsuder/IEU.Core#17]
![image](https://user-images.githubusercontent.com/12688256/91658607-347c3680-ea8f-11ea-9230-04118f1586e4.png)
unsure what I am doing wrong here

**Comment by ptrsuder** [comment]
Can you make sure that you have tiles in results folder for these frames? It should be **[filename]**_tile_00 and the like.

**Comment by NetyashaRoozi** [comment]
iirc the results folder was blank at the time and was never written to

**Comment by ptrsuder** [comment]
Maybe you processed images in memory then (in settings)

**Comment by NetyashaRoozi** [comment]
It won't allow me to run with that setting on. There is output it's just in the LR folder, I'll try moving those files into results later to see if it works then

**Comment by NetyashaRoozi** [comment]
and by output I mean, the sections that are upscaled are there, not the full image

**Comment by NetyashaRoozi** [comment]
moving the files gives several errors, like dividing by zero, failed to read file and skipping
